plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://questioning-machine.github.io
baseurl: /depsek

title: Questioning Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

machine:
  name: Questioning-Machine
  verb: Questioning
  instructions_file: questioning.md
  token: depsek
  server: https://localhost:443
  apiUrl: https://api.deepseek.com/chat/completions

app:
  worker_name: depsekapi.js

lm:
  model: deepseek-chat
  max_tokens: 8192
  presence_penalty: 0.0
  frequency_penalty: 0.0
  temperature: 1.0
  top_p: 0.95

github_settings:
  owner: questioning-machine
  repo: questioning_machine
  file_name: machina.yaml
  branch: main
  token_file: github.txt
